version: '3'

services:
  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka
    networks:
      - broker-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: kafdrop
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  producer:
    image: uluizeduardo/str-producer:v2024.0.0.1
    container_name: producer
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_HOST: kafka:9092

  consumer:
    image: uluizeduardo/str-consumer:v2024.0.0.1
    container_name: consumer
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - producer
    environment:
      KAFKA_HOST: kafka:9092

networks:
  broker-kafka:
    driver: bridge

volumes:
  dados_kafka:
    driver: local